spring:
  application:
    name: SyllabusSync
  
  datasource: 
    url: ${syllabussync.mysql.database.azure.com}
    username: ${dbadmin}
    password: ${SeniorProject!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true 


